apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs-buildbot-master-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  #persistentVolumeReclaimPolicy: Retain
  storageClassName: rook-block
  resources:
    requests:
      storage: 1Gi