apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cvmfs-buildbot-nginx
spec:
  selector:
    matchLabels:
      app: cvmfs-buildbot-nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cvmfs-buildbot-nginx
        type: nginx
    spec:
      containers:
      - name: buildbot-nginx
        image: nginx:1.13-alpine
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: cvmfs-buildbot-nginx-config
          mountPath: /etc/nginx/conf.d/
        - name: cvmfs-buildbot-secrets
          mountPath: /opt/
        ports:
        - containerPort: 443
          name: https
          protocol: TCP
      volumes:
      - name: cvmfs-buildbot-nginx-config
        configMap:
          name: cvmfs-buildbot-nginx-cfg
          items:
          - key: nginx.conf
            path: nginx.conf
      - name: cvmfs-buildbot-secrets
        secret:
          secretName: cvmfs-buildbot
          items:
          - key: htaccess
            path: .htaccess
          - key: sslcert
            path: server.crt
          - key: sslkey
            path: server.key
